### ISSUE TITLE
Undefined is not an object Proptypes.oneOf

### ISSUE THREAD

**Issue by LorandP** [quocnguyenvan/react-native-animated-message#1]
I get this error when trying to use it.
undefined is not an object(evaluating '_react2.PropTypes.oneOf')

It didn't work when it was unlinked and than I linked it, it doesn't work either way.

"react-native-animated-message": "^1.0.1",
"react-native": "0.50.0",

**Comment by quocvn** [comment]
React.PropTypes has moved into a different package since React v15.5. Please use the prop-types library instead.
Refer at: https://reactjs.org/docs/typechecking-with-proptypes.html
